version: "3.9"

services:
  kong-database:
    image: postgres:9.6-alpine
    container_name: kong-database
    restart: on-failure
    environment:
      POSTGRES_USER: pg-user
      POSTGRES_PASSWORD: pg-password
      POSTGRES_DB: kong
    ports:
      - 5432:5432
    networks:
      - kong-gateway
    volumes:
      - kong-database:/var/lib/postgresql/data

networks:
  kong-gateway:
    external: true

volumes:
  kong-database:
